# Generated by Django 3.2.7 on 2021-10-01 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TmabTbKt10',
            fields=[
                ('appl_no', models.CharField(blank=True, max_length=20, primary_key=True, serialize=False)),
                ('appl_date', models.CharField(blank=True, max_length=20, null=True)),
                ('pub_no', models.CharField(blank=True, max_length=20, null=True)),
                ('pub_date', models.CharField(blank=True, max_length=20, null=True)),
                ('reg_no', models.CharField(blank=True, max_length=20, null=True)),
                ('reg_date', models.CharField(blank=True, max_length=20, null=True)),
                ('tm_name_kor', models.CharField(blank=True, max_length=1000, null=True)),
                ('tm_name_eng', models.CharField(blank=True, max_length=1000, null=True)),
                ('final_decision_code', models.CharField(blank=True, max_length=5, null=True)),
                ('final_decision_code_name', models.CharField(blank=True, max_length=300, null=True)),
                ('final_decision_date', models.CharField(blank=True, max_length=8, null=True)),
                ('tm_category_code', models.CharField(blank=True, max_length=5, null=True)),
                ('tm_category_code_name', models.CharField(blank=True, max_length=300, null=True)),
                ('tm_class_code', models.CharField(blank=True, max_length=5, null=True)),
                ('tm_class_code_name', models.CharField(blank=True, max_length=300, null=True)),
                ('goods_class_ver', models.CharField(blank=True, max_length=5, null=True)),
                ('has_tm_image', models.CharField(blank=True, max_length=5, null=True)),
                ('has_pub', models.CharField(blank=True, max_length=5, null=True)),
                ('has_amend_pub', models.CharField(blank=True, max_length=5, null=True)),
                ('has_ori_appl', models.CharField(blank=True, max_length=5, null=True)),
                ('has_trial', models.CharField(blank=True, max_length=5, null=True)),
                ('has_priority', models.CharField(blank=True, max_length=5, null=True)),
                ('intl_reg_no', models.CharField(blank=True, max_length=20, null=True)),
                ('intl_reg_no_date', models.CharField(blank=True, max_length=20, null=True)),
                ('subsequent_designation_date', models.CharField(blank=True, max_length=20, null=True)),
                ('final_retro_code', models.CharField(blank=True, max_length=20, null=True)),
                ('final_retro_code_name', models.CharField(blank=True, max_length=300, null=True)),
                ('final_retro_date', models.CharField(blank=True, max_length=20, null=True)),
                ('tm_name_date', models.CharField(blank=True, max_length=20, null=True)),
                ('exp_date', models.CharField(blank=True, max_length=20, null=True)),
                ('init_update_date', models.CharField(blank=True, max_length=50, null=True)),
                ('final_modified_date', models.CharField(blank=True, max_length=50, null=True)),
                ('legal_status', models.CharField(blank=True, max_length=20, null=True)),
                ('is_service_start', models.CharField(blank=True, max_length=5, null=True)),
                ('pub_reg_no', models.CharField(blank=True, max_length=20, null=True)),
                ('pub_reg_date', models.CharField(blank=True, max_length=20, null=True)),
                ('is_full_pub_reg', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'tmab_tb_kt10',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TmabTbKt13',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appl_no', models.CharField(blank=True, max_length=20, null=True)),
                ('priority_serial_no', models.IntegerField(blank=True, null=True)),
                ('priority_appl_no', models.CharField(blank=True, max_length=100, null=True)),
                ('priority_appl_date', models.CharField(blank=True, max_length=20, null=True)),
                ('priority_country_code', models.CharField(blank=True, max_length=8, null=True)),
                ('priority_country_code_name', models.CharField(blank=True, max_length=150, null=True)),
                ('init_update_date', models.CharField(blank=True, max_length=20, null=True)),
                ('final_modified_date', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'tmab_tb_kt13',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TmabTbKt14',
            fields=[
                ('appl_no', models.CharField(blank=True, max_length=20, primary_key=True, serialize=False)),
                ('ori_appl_no', models.CharField(blank=True, max_length=20, null=True)),
                ('ori_appl_date', models.CharField(blank=True, max_length=20, null=True)),
                ('init_update_date', models.CharField(blank=True, max_length=20, null=True)),
                ('final_modified_date', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'tmab_tb_kt14',
                'managed': False,
            },
        ),
    ]
